export const villains = [
  {
    id: 1,
    name: "Freddy Krueger",
    movie: "A Nightmare on Elm Street",
    quote:
      "You have nothing to worry about. This... won't hurt one... little... bit.",
    pic: "/images/freddy.jpg",
  },
  {
    id: 2,
    name: "Jason Voorhees",
    movie: "Friday the 13th",
    quote: "...",
    pic: "/images/jason.jpeg",
  },
  {
    id: 3,
    name: "Michael Myers",
    movie: "Halloween",
    quote: "...",
    pic: "/images/michael.webp",
  },
  {
    id: 4,
    name: "Leatherface",
    movie: "The Texas Chainsaw Massacre",
    quote: "...",
    pic: "/images/leatherface.webp",
  },
  {
    id: 5,
    name: "Chucky",
    movie: "Child's Play",
    quote: "Hi, I'm Chucky. Want to play?",
    pic: "/images/chucky.webp",
  },
  {
    id: 6,
    name: "Ghostface",
    movie: "Scream",
    quote: "What's your favorite scary movie?",
    pic: "/images/scream.jpg",
  },
  {
    id: 7,
    name: "The Witch",
    movie: "The Witch",
    quote: "Wouldst thou like to live deliciously?",
    pic: "/images/witch.webp",
  },
  {
    id: 8,
    name: "Pennywise",
    movie: "IT",
    quote: "You'll float too.",
    pic: "/images/pennywise.webp",
  },
  {
    id: 9,
    name: "Hannibal Lecter",
    movie: "Silence of the Lambs",
    quote: "I ate his liver with some fava beans and a nice chianti.",
    pic: "/images/hannibal.webp",
  },
  {
    id: 10,
    name: "Jigsaw",
    movie: "Saw",
    quote: "I want to play a game.",
    pic: "/images/jigsaw.webp",
  },
  {
    id: 11,
    name: "Samara Morgan",
    movie: "The Ring",
    quote: "Seven days.",
    pic: "/images/samara.webp",
  },
  {
    id: 12,
    name: "Jack Torrance",
    movie: "The Shining",
    quote: "Here's Johnny!",
    pic: "/images/jacktorrance.webp",
  },
  {
    id: 13,
    name: "Patrick Bateman",
    movie: "American Psycho",
    quote: "I have to return some videotapes.",
    pic: "/images/patrickbateman.jpg",
  },
  {
    id: 14,
    name: "Carrie White",
    movie: "Carrie",
    quote: "They're all gonna laugh at you!",
    pic: "/images/carrie.jpg",
  },
  {
    id: 15,
    name: "Frankenstein's Monster",
    movie: "Frankenstein",
    quote: "...",
    pic: "/images/frankenstein.webp",
  },
  {
    id: 16,
    name: "Regan MacNeil",
    movie: "The Exorcist",
    quote:
      "Your mother's in here, Karras. Would you like to leave a message? I'll see that she gets it.",
    pic: "/images/exorcist.webp",
  },
  {
    id: 17,
    name: "Dracula",
    movie: "Dracula",
    quote: "Listen to them. Children of the night. What music they make.",
    pic: "/images/dracula.webp",
  },
  {
    id: 18,
    name: "The Nun",
    movie: "The Nun",
    quote: "...",
    pic: "/images/nun.jpg",
  },
  {
    id: 19,
    name: "Art the Clown",
    movie: "Terrifier",
    quote: "...",
    pic: "/images/terrifier.jpg",
  },
  {
    id: 20,
    name: "Annabelle",
    movie: "The Conjuring",
    quote: "...",
    pic: "/images/annabelle.webp",
  },
];
